version: '3'

services:

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181
        networks:
            - challengenetwork

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        restart: always
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        networks:
            - challengenetwork
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        networks:
            - challengenetwork
        command: mongod --smallfiles --logpath=/dev/null

    challenge:
        build:
            context: ./
            dockerfile: Dockerfile
        image: challenge
        depends_on:
            - mongodb
            - kafka
        volumes:
            - ./data/logs:/data/logs
        ports:
            - 9090:9090
        networks:
            - challengenetwork

networks:
    challengenetwork:
